### ISSUE TITLE
image filenames with spaces not supported?

### ISSUE THREAD

**Issue by curtislisle** [abcsFrederick/FIBSEM#3]
I tried testing the auto-execution feature with several different images.  It seems that an image file with an embedded space did not work when executed on linux.  Specifically, the file "./P9\ B27-29220-27404.jpg" didn't work.  Maybe the slash and space are messing up the shell script.  

If this is a true and repeatable problem, it could be addressed by simply instructing users not to allow spaces in image filenames.

**Comment by tymiao1220** [comment]
commit#0a4fe89 addressed this issue
